package com.company.speedment.test.twitter;

import com.speedment.internal.core.runtime.ApplicationMetadata;
import javax.annotation.Generated;

/**
 * A {@link com.speedment.internal.core.runtime.ApplicationMetadata} class for
 * the {@link com.speedment.config.Project} named twitter. This class contains
 * the meta data present at code generation time.
 * <p>
 * This Class or Interface has been automatically generated by Speedment. Any
 * changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment
 */
@Generated("Speedment")
public class TwitterApplicationMetadata implements ApplicationMetadata {

	private final static StringBuilder METADATA = new StringBuilder();

	static {
		METADATA.append("import com.speedment.config.parameters.*\n");
		METADATA.append("\n");
		METADATA.append("name = \"twitter\";\n");
		METADATA.append("packageLocation = \"src/main/java\";\n");
		METADATA.append("packageName = \"com.company.speedment.test\";\n");
		METADATA.append("enabled = true;\n");
		METADATA.append("expanded = true;\n");
		METADATA.append("dbms {\n");
		METADATA.append("    ipAddress = \"127.0.0.1\";\n");
		METADATA.append("    name = \"db0\";\n");
		METADATA.append("    port = 3306;\n");
		METADATA.append("    typeName = \"MySQL\";\n");
		METADATA.append("    username = \"root\";\n");
		METADATA.append("    enabled = true;\n");
		METADATA.append("    expanded = true;\n");
		METADATA.append("    schema {\n");
		METADATA.append("        columnCompressionType = ColumnCompressionType.NONE;\n");
		METADATA.append("        fieldStorageType = FieldStorageType.WRAPPER;\n");
		METADATA.append("        name = \"twitter\";\n");
		METADATA.append("        schemaName = \"twitter\";\n");
		METADATA.append("        storageEngineType = StorageEngineType.ON_HEAP;\n");
		METADATA.append("        defaultSchema = false;\n");
		METADATA.append("        enabled = true;\n");
		METADATA.append("        expanded = true;\n");
		METADATA.append("        table {\n");
		METADATA.append("            columnCompressionType = ColumnCompressionType.INHERIT;\n");
		METADATA.append("            fieldStorageType = FieldStorageType.INHERIT;\n");
		METADATA.append("            name = \"tweets\";\n");
		METADATA.append("            storageEngineType = StorageEngineType.INHERIT;\n");
		METADATA.append("            tableName = \"tweets\";\n");
		METADATA.append("            enabled = true;\n");
		METADATA.append("            expanded = true;\n");
		METADATA.append("            column {\n");
		METADATA.append("                columnCompressionType = ColumnCompressionType.INHERIT;\n");
		METADATA.append("                databaseType = java.lang.Integer.class;\n");
		METADATA.append("                fieldStorageType = FieldStorageType.INHERIT;\n");
		METADATA.append("                name = \"id\";\n");
		METADATA.append(
				"                typeMapper = com.speedment.internal.core.config.mapper.identity.IntegerIdentityMapper.class;\n");
		METADATA.append("                autoincrement = true;\n");
		METADATA.append("                enabled = true;\n");
		METADATA.append("                expanded = true;\n");
		METADATA.append("                nullable = false;\n");
		METADATA.append("            }\n");
		METADATA.append("            column {\n");
		METADATA.append("                columnCompressionType = ColumnCompressionType.INHERIT;\n");
		METADATA.append("                databaseType = java.lang.String.class;\n");
		METADATA.append("                fieldStorageType = FieldStorageType.INHERIT;\n");
		METADATA.append("                name = \"user\";\n");
		METADATA.append(
				"                typeMapper = com.speedment.internal.core.config.mapper.identity.StringIdentityMapper.class;\n");
		METADATA.append("                autoincrement = false;\n");
		METADATA.append("                enabled = true;\n");
		METADATA.append("                expanded = true;\n");
		METADATA.append("                nullable = false;\n");
		METADATA.append("            }\n");
		METADATA.append("            column {\n");
		METADATA.append("                columnCompressionType = ColumnCompressionType.INHERIT;\n");
		METADATA.append("                databaseType = java.sql.Timestamp.class;\n");
		METADATA.append("                fieldStorageType = FieldStorageType.INHERIT;\n");
		METADATA.append("                name = \"createdAt\";\n");
		METADATA.append(
				"                typeMapper = com.speedment.internal.core.config.mapper.identity.TimestampIdentityMapper.class;\n");
		METADATA.append("                autoincrement = false;\n");
		METADATA.append("                enabled = true;\n");
		METADATA.append("                expanded = true;\n");
		METADATA.append("                nullable = false;\n");
		METADATA.append("            }\n");
		METADATA.append("            column {\n");
		METADATA.append("                columnCompressionType = ColumnCompressionType.INHERIT;\n");
		METADATA.append("                databaseType = java.lang.String.class;\n");
		METADATA.append("                fieldStorageType = FieldStorageType.INHERIT;\n");
		METADATA.append("                name = \"text\";\n");
		METADATA.append(
				"                typeMapper = com.speedment.internal.core.config.mapper.identity.StringIdentityMapper.class;\n");
		METADATA.append("                autoincrement = false;\n");
		METADATA.append("                enabled = true;\n");
		METADATA.append("                expanded = true;\n");
		METADATA.append("                nullable = false;\n");
		METADATA.append("            }\n");
		METADATA.append("            column {\n");
		METADATA.append("                columnCompressionType = ColumnCompressionType.INHERIT;\n");
		METADATA.append("                databaseType = java.lang.String.class;\n");
		METADATA.append("                fieldStorageType = FieldStorageType.INHERIT;\n");
		METADATA.append("                name = \"source\";\n");
		METADATA.append(
				"                typeMapper = com.speedment.internal.core.config.mapper.identity.StringIdentityMapper.class;\n");
		METADATA.append("                autoincrement = false;\n");
		METADATA.append("                enabled = true;\n");
		METADATA.append("                expanded = true;\n");
		METADATA.append("                nullable = false;\n");
		METADATA.append("            }\n");
		METADATA.append("            column {\n");
		METADATA.append("                columnCompressionType = ColumnCompressionType.INHERIT;\n");
		METADATA.append("                databaseType = java.lang.String.class;\n");
		METADATA.append("                fieldStorageType = FieldStorageType.INHERIT;\n");
		METADATA.append("                name = \"isTruncated\";\n");
		METADATA.append(
				"                typeMapper = com.speedment.internal.core.config.mapper.identity.StringIdentityMapper.class;\n");
		METADATA.append("                autoincrement = false;\n");
		METADATA.append("                enabled = true;\n");
		METADATA.append("                expanded = true;\n");
		METADATA.append("                nullable = false;\n");
		METADATA.append("            }\n");
		METADATA.append("            column {\n");
		METADATA.append("                columnCompressionType = ColumnCompressionType.INHERIT;\n");
		METADATA.append("                databaseType = java.lang.Integer.class;\n");
		METADATA.append("                fieldStorageType = FieldStorageType.INHERIT;\n");
		METADATA.append("                name = \"inReplyToStatusId\";\n");
		METADATA.append(
				"                typeMapper = com.speedment.internal.core.config.mapper.identity.IntegerIdentityMapper.class;\n");
		METADATA.append("                autoincrement = false;\n");
		METADATA.append("                enabled = true;\n");
		METADATA.append("                expanded = true;\n");
		METADATA.append("                nullable = true;\n");
		METADATA.append("            }\n");
		METADATA.append("            column {\n");
		METADATA.append("                columnCompressionType = ColumnCompressionType.INHERIT;\n");
		METADATA.append("                databaseType = java.lang.Integer.class;\n");
		METADATA.append("                fieldStorageType = FieldStorageType.INHERIT;\n");
		METADATA.append("                name = \"inReplyToUserId\";\n");
		METADATA.append(
				"                typeMapper = com.speedment.internal.core.config.mapper.identity.IntegerIdentityMapper.class;\n");
		METADATA.append("                autoincrement = false;\n");
		METADATA.append("                enabled = true;\n");
		METADATA.append("                expanded = true;\n");
		METADATA.append("                nullable = true;\n");
		METADATA.append("            }\n");
		METADATA.append("            column {\n");
		METADATA.append("                columnCompressionType = ColumnCompressionType.INHERIT;\n");
		METADATA.append("                databaseType = java.lang.String.class;\n");
		METADATA.append("                fieldStorageType = FieldStorageType.INHERIT;\n");
		METADATA.append("                name = \"isFavorited\";\n");
		METADATA.append(
				"                typeMapper = com.speedment.internal.core.config.mapper.identity.StringIdentityMapper.class;\n");
		METADATA.append("                autoincrement = false;\n");
		METADATA.append("                enabled = true;\n");
		METADATA.append("                expanded = true;\n");
		METADATA.append("                nullable = false;\n");
		METADATA.append("            }\n");
		METADATA.append("            column {\n");
		METADATA.append("                columnCompressionType = ColumnCompressionType.INHERIT;\n");
		METADATA.append("                databaseType = java.lang.String.class;\n");
		METADATA.append("                fieldStorageType = FieldStorageType.INHERIT;\n");
		METADATA.append("                name = \"inReplyToScreenName\";\n");
		METADATA.append(
				"                typeMapper = com.speedment.internal.core.config.mapper.identity.StringIdentityMapper.class;\n");
		METADATA.append("                autoincrement = false;\n");
		METADATA.append("                enabled = true;\n");
		METADATA.append("                expanded = true;\n");
		METADATA.append("                nullable = false;\n");
		METADATA.append("            }\n");
		METADATA.append("            primaryKeyColumn {\n");
		METADATA.append("                name = \"id\";\n");
		METADATA.append("                enabled = true;\n");
		METADATA.append("                expanded = true;\n");
		METADATA.append("            }\n");
		METADATA.append("            index {\n");
		METADATA.append("                name = \"PRIMARY\";\n");
		METADATA.append("                enabled = true;\n");
		METADATA.append("                expanded = true;\n");
		METADATA.append("                unique = true;\n");
		METADATA.append("                indexColumn {\n");
		METADATA.append("                    name = \"id\";\n");
		METADATA.append("                    orderType = OrderType.ASC;\n");
		METADATA.append("                    enabled = true;\n");
		METADATA.append("                    expanded = true;\n");
		METADATA.append("                }\n");
		METADATA.append("            }\n");
		METADATA.append("        }\n");
		METADATA.append("    }\n");
		METADATA.append("}\n");
	}

	@Override
	public String getMetadata() {
		return METADATA.toString();
	}
}