package com.company.speedment.test.twitter;

import com.company.speedment.test.twitter.db0.twitter.tweets.Tweets;
import com.company.speedment.test.twitter.db0.twitter.tweets.impl.TweetsManagerImpl;
import com.speedment.internal.core.runtime.SpeedmentApplicationLifecycle;

import java.sql.Timestamp;

import javax.annotation.Generated;

/**
 * A {@link com.speedment.internal.core.runtime.SpeedmentApplicationLifecycle}
 * class for the {@link com.speedment.config.Project} named twitter.
 * <p>
 * This Class or Interface has been automatically generated by Speedment. Any
 * changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment
 */
@Generated("Speedment")
public class TwitterApplication extends SpeedmentApplicationLifecycle<TwitterApplication> {

	public TwitterApplication() {
		setSpeedmentApplicationMetadata(new TwitterApplicationMetadata());
	}

	@Override
	protected void onInit() {
		super.onInit();
		loadAndSetProject();
		TweetsManagerImpl manager = new TweetsManagerImpl(speedment);
		put(manager);

		Tweets tweets = manager.newInstance();

		tweets.setCreatedAt(new Timestamp(System.currentTimeMillis())).setInReplyToScreenName("replyName")
				.setInReplyToStatusId(1);

	}
}